fix k3s production deployment workflow

diff --git a/.github/workflows/k3s-deploy.yml b/.github/workflows/k3s-deploy.yml
--- a/.github/workflows/k3s-deploy.yml
+++ b/.github/workflows/k3s-deploy.yml
@@ -13,7 +13,8 @@ permissions:
 
 env:
   AWS_REGION: us-east-1
-  ECR_REPOSITORY: diabetes-app
+  ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
+  ECR_REPOSITORY: db-risk-app
   K8S_DEPLOYMENT: diabetes-api
   K8S_CONTAINER: diabetes-api
 
@@ -55,7 +56,7 @@ jobs:
   build:
     name: Build Scan Push Image
     needs: test
-    if: github.ref == 'refs/heads/main'
+    if: github.ref == 'refs/heads/ver/new_upgrade'
     runs-on: ubuntu-latest
 
 
@@ -75,7 +76,7 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume:
-            arn:aws:iam::<ACCOUNT_ID>:role/github-actions-deploy
+            arn:aws:iam::${{vars.ACCOUNT_ID}}:role/github-actions-deploy
 
           aws-region:
             ${{env.AWS_REGION}}
@@ -125,24 +126,116 @@ jobs:
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume:
-            arn:aws:iam::<ACCOUNT_ID>:role/github-actions-deploy
+            arn:aws:iam::${{vars.ACCOUNT_ID}}:role/github-actions-deploy
           aws-region:
             ${{env.AWS_REGION}}
 
-
-      - name: Deploy using SSM
+      - name: Deploy using SSM with validation
+        shell: bash
         run: |
           IMAGE_TAG=${{needs.build.outputs.image_tag}}
-          aws ssm send-command \
+          echo "Deploying VERSION: $IMAGE_TAG"
+
+          IMAGE=${{vars.ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPOSITORY}}:${IMAGE_TAG}
+          echo "Deploying image:"
+          echo $IMAGE
+
+          COMMAND_ID=$(aws ssm send-command \
           --instance-ids "${{secrets.EC2_INSTANCE_ID}}" \
           --document-name "AWS-RunShellScript" \
           --comment "Deploy diabetes api ${IMAGE_TAG}" \
-          --parameters commands='[
-          "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml",
-          "ACCOUNT=$(aws sts get-caller-identity --query Account --output text)",
-          "IMAGE=$ACCOUNT.dkr.ecr.me-central-1.amazonaws.com/diabetes-app:'${IMAGE_TAG}'",
-          "kubectl set image deployment/diabetes-api diabetes-api=$IMAGE",
-          "kubectl rollout status deployment/diabetes-api --timeout=180s",
-          "kubectl get pods"
-          ]'
+
+          --parameters commands="[
+          \"export KUBECONFIG=/etc/rancher/k3s/k3s.yaml\",
+
+          \"kubectl set image deployment/${K8S_DEPLOYMENT} \
+          -n diabetes-prod \
+          ${K8S_CONTAINER}=${IMAGE}\",
+
+          \"kubectl annotate deployment ${K8S_DEPLOYMENT} \
+          -n diabetes-prod \
+          build=${IMAGE_TAG} \
+          --overwrite\",
+
+          \"kubectl rollout status deployment/${K8S_DEPLOYMENT} \
+          -n diabetes-prod \
+          --timeout=180s || \
+          (kubectl rollout undo deployment/${K8S_DEPLOYMENT} \
+          -n diabetes-prod && exit 1)\",
+
+
+          \"kubectl wait \
+          --for=condition=ready \
+          pod \
+          -l app=diabetes-api \
+          -n diabetes-prod \
+          --timeout=120s\",
+
+          \"kubectl get pods \
+          -n diabetes-prod \
+          -o wide\",
+
+          \"kubectl describe deployment/${K8S_DEPLOYMENT} \
+          -n diabetes-prod\"
+
+          ]" \
+          --query "Command.CommandId" \
+          --output text \
+          --region ${{env.AWS_REGION}})
+
+
+          echo "SSM COMMAND ID:"
+          echo $COMMAND_ID
+
+
+          echo "Waiting for EC2 deployment..."
+
+          aws ssm wait command-executed \
+          --command-id $COMMAND_ID \
+          --instance-id "${{secrets.EC2_INSTANCE_ID}}" \
           --region ${{env.AWS_REGION}}
+
+
+          STATUS=$(aws ssm get-command-invocation \
+          --command-id $COMMAND_ID \
+          --instance-id "${{secrets.EC2_INSTANCE_ID}}" \
+          --query "Status" \
+          --output text \
+          --region ${{env.AWS_REGION}})
+
+
+          echo "Deployment STATUS:"
+          echo $STATUS
+
+
+          echo "----- OUTPUT -----"
+
+
+          aws ssm get-command-invocation \
+          --command-id $COMMAND_ID \
+          --instance-id "${{secrets.EC2_INSTANCE_ID}}" \
+          --query "StandardOutputContent" \
+          --output text \
+          --region ${{env.AWS_REGION}}
+
+
+          echo "----- ERROR -----"
+
+
+          aws ssm get-command-invocation \
+          --command-id $COMMAND_ID \
+          --instance-id "${{secrets.EC2_INSTANCE_ID}}" \
+          --query "StandardErrorContent" \
+          --output text \
+          --region ${{env.AWS_REGION}}
+
+
+
+          if [ "$STATUS" != "Success" ]
+          then
+              echo "Deployment failed"
+              exit 1
+          fi
+
+
+          echo "Deployment completed successfully"
