k3s deployment file update

diff --git a/.github/workflows/k3s-deploy.yml b/.github/workflows/k3s-deploy.yml
--- a/.github/workflows/k3s-deploy.yml
+++ b/.github/workflows/k3s-deploy.yml
@@ -161,14 +161,16 @@ jobs:
           COMMAND_ID=$(aws ssm send-command \
           --instance-ids "${{secrets.EC2_INSTANCE_ID}}" \
           --document-name "AWS-RunShellScript" \
+          --timeout-seconds 900 \
           --comment "Deploy diabetes api ${IMAGE_TAG}" \
           --parameters '{
             "commands": [
               "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml",
               "kubectl set image deployment/'"${K8S_DEPLOYMENT}"' -n diabetes-prod '"${K8S_CONTAINER}"'='"${IMAGE}"'",
               "kubectl annotate deployment '"${K8S_DEPLOYMENT}"' -n diabetes-prod build='"${IMAGE_TAG}"' --overwrite",
-              "kubectl rollout status deployment/'"${K8S_DEPLOYMENT}"' -n diabetes-prod --timeout=180s || (kubectl rollout undo deployment/'"${K8S_DEPLOYMENT}"' -n diabetes-prod && exit 1)",
+              "kubectl rollout status deployment/'"${K8S_DEPLOYMENT}"' -n diabetes-prod --timeout=300s || (kubectl rollout undo deployment/'"${K8S_DEPLOYMENT}"' -n diabetes-prod && exit 1)",
               "kubectl wait --for=condition=ready pod -l app=diabetes-api -n diabetes-prod --timeout=120s",
+              "kubectl get deployment '"${K8S_DEPLOYMENT}"' -n diabetes-prod -o jsonpath='{.status.availableReplicas}'",
               "kubectl get pods -n diabetes-prod -o wide",
               "kubectl describe deployment/'"${K8S_DEPLOYMENT}"' -n diabetes-prod"
             ]
@@ -182,10 +184,32 @@ jobs:
 
           echo "Waiting for EC2 deployment..."
 
-          aws ssm wait command-executed \
-          --command-id $COMMAND_ID \
-          --instance-id "${{secrets.EC2_INSTANCE_ID}}" \
-          --region ${{env.AWS_REGION}}
+          echo "Waiting for SSM command completion..."
+
+          for i in {1..60}
+          do
+            STATUS=$(aws ssm get-command-invocation \
+              --command-id $COMMAND_ID \
+              --instance-id "${{secrets.EC2_INSTANCE_ID}}" \
+              --query "Status" \
+              --output text \
+              --region ${{env.AWS_REGION}})
+
+            echo "SSM status: $STATUS"
+
+            if [ "$STATUS" = "Success" ]; then
+                break
+            fi
+
+            if [ "$STATUS" = "Failed" ] || \
+              [ "$STATUS" = "Cancelled" ] || \
+              [ "$STATUS" = "TimedOut" ]; then
+                echo "SSM command failed"
+                exit 1
+            fi
+
+            sleep 10
+          done
 
           STATUS=$(aws ssm get-command-invocation \
           --command-id $COMMAND_ID \
